OPT = -fast -fnonstd
DEBUGOPT = -O0 -ftrap=common
CXX = CC
CXXFLAGS = ${OPT} -g -library=stlport4
LDFLAGS = ${OPT} -g -library=stlport4
NO_TRAP_FLAGS = "-ftrap=%none"

KERNEL := $(shell uname -s)
ifeq ($(KERNEL),Linux)
  LDFLAGS += -Yl,/usr/bin
endif
