#!/bin/bash

export GXX="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-g++"
export LD_GOLD="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld.gold"
export DEBUG_CPPFLAGS="-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem /home/shreyas/anaconda3/include"
export DEBUG_CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/shreyas/anaconda3/include"
export GCC_NM="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc-nm"
export GCC_RANLIB="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib"
export CFLAGS="-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/shreyas/anaconda3/include"
export GCC_AR="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc-ar"
export CC="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc"
export READELF="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-readelf"
export CXXFLAGS="-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/shreyas/anaconda3/include"
export OBJCOPY="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-objcopy"
export ADDR2LINE="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-addr2line"
export CMAKE_PREFIX_PATH="/home/shreyas/anaconda3:/home/shreyas/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot/usr"
export RANLIB="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ranlib"
export OBJDUMP="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-objdump"
export AS="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-as"
export AR="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ar"
export NM="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-nm"
export CONDA_BUILD_SYSROOT="/home/shreyas/anaconda3/x86_64-conda_cos6-linux-gnu/sysroot"
export DEBUG_CXXFLAGS="-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem /home/shreyas/anaconda3/include"
export CXX="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++"
export CXXFILT="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++filt"
export ELFEDIT="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-elfedit"
export CPPFLAGS="-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/shreyas/anaconda3/include"
export LDFLAGS="-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/shreyas/anaconda3/lib -Wl,-rpath-link,/home/shreyas/anaconda3/lib -L/home/shreyas/anaconda3/lib"
export GCC="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-gcc"
export SIZE="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-size"
export CPP="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cpp"
export LD="/home/shreyas/anaconda3/bin/x86_64-conda_cos6-linux-gnu-ld"

g++ -ansi -O3 -ftrapping-math -fno-math-errno  -ftree-vectorize -Wall -W  -DSVN_REVISION=\"exported\" -DSYS_CONFIG=\"/media/toma/D/shreyas/TPCI/c13.01/source/cloudyconfig.h\"  -c -o mole_solve.o mole_solve.cpp
